# file: roles/php/tasks/main.yml

- name: add remi repository
  yum: name=http://rpms.famillecollet.com/enterprise/remi-release-7.rpm state=installed

- name: install php packages
  yum: name={{ item }} state=present enablerepo=remi-php56
  with_items:
    - php
    - php-mysqlnd
    - php-pecl-memcached
    - composer

- name: set php.ini timezone
  lineinfile:
    dest: /etc/php.ini
    backrefs: yes
    regexp: '^;date.timezone =$'
    line: 'date.timezone = Asia/Tokyo'
